function res = power_vector2_derivative(x,pdeg)
%function res = power_vector2_derivative(x,pdeg)
%
% function computing the derivative of the power-vector, which is
% the vector of all monomials of degree pdeg of
% the vector x, which is assumed to be 2-dimensional (resp: only
% first two entries are used)
%
% res hence is a jacobian matrix of size num_monomials x 2 matrix.

% This program is open source.  For license terms, see the COPYING file.
%
% --------------------------------------------------------------------
% ATTRIBUTION NOTICE:
% This product includes software developed for the RBmatlab project at
% (C) Universities of Stuttgart and Münster, Germany.
%
% RBmatlab is a MATLAB software package for model reduction with an
% emphasis on Reduced Basis Methods. The project is maintained by
% M. Dihlmann, M. Drohmann, B. Haasdonk, M. Ohlberger and M. Schaefer.
% For Online Documentation and Download we refer to www.morepas.org.
% --------------------------------------------------------------------


% Bernard Haasdonk 28.8.2009

switch pdeg
 case 0
%  res = [1];
  res =[0,0];
 case 1
  %  res = [1;x(:)];
  res = [0,0 ; ...
	 1,0 ; ...
	 0,1 ];
 case 2
%  res = [1,x(1),x(2),x(1)^2, x(1)*x(2),x(2)^2]';
%  res = [1,x(1),x(2),x(1)^2, x(1)*x(2),x(2)^2]';
  res = [0,0 ; ...
	 1,0 ; ...
	 0,1 ; ...
	 2*x(1),0 ; ...
	 x(2),x(1) ; ...
	 0,2*x(2)];
 case 3
%  res = [1,x(1),x(2),x(1)^2, x(1)*x(2),x(2)^2,...
%	 x(1)^3, x(1)^2*x(2), x(1) * x(2)^2, x(2)^3]';
  res = [0,0 ; ...
	 1,0 ; ...
	 0,1 ; ...
	 2*x(1),0 ; ...
	 x(2),x(1) ; ...
	 0,2*x(2) ; ...
	 3*x(1)^2, 0; ...
	 2*x(1)*x(2),x(1)^2; ...
	 x(2)^2,x(1)*x(2)*2; ...
	 0, 3*x(2)^2];
 case 4
%  res = [1,x(1),x(2),x(1)^2, x(1)*x(2),x(2)^2,...
%	 x(1)^3, x(1)^2*x(2), x(1) * x(2)^2, x(2)^3,...
%	 x(1)^4, x(1)^3*x(2), x(1)^2*x(2)^2, x(1)* x(2)^3, x(2)^4]';
  res = [0,0 ; ...
	 1,0 ; ...
	 0,1 ; ...
	 2*x(1),0 ; ...
	 x(2),x(1) ; ...
	 0,2*x(2) ; ...
	 3*x(1)^2, 0; ...
	 2*x(1)*x(2),x(1)^2; ...
	 x(2)^2,x(1)*x(2)*2; ...
	 0, 3*x(2)^2; ...
	 4*x(1)^3, 0; ...
	 3*x(1)^2*x(2), x(1)^3; ...
	 2*x(1)*x(2)^2,x(1)^2*2*x(2); ...
	 x(2)^3,x(1)*3* x(2)^2; ...
	 0,4*x(2)^3];
 otherwise
  error('powervector not defined for desired pdeg')
end;
%| \docupdate 
