    min_eigen_value = [1e-8 1e-10];
    max_reduced_basis = [k(temp2) k(temp2)];
    
    inner_product_matrix_velocity = ldg_mass_matrix(params,grid,params);% ...
    %+ ldg_h1_seminorm_mass_matrix_assembly(params,grid);
    
    [ reduced_basis_matrix_B_velocity, eigen_values_velocity, ...
        error_estimate_velocity] = ...
        pod_extension_velocity( snapshot_matrix_velocity, params, min_eigen_value, ...
        max_reduced_basis, inner_product_matrix_velocity);
    
    min_eigen_value = [1e-10];
    max_reduced_basis = max(k);
    
        [ reduced_basis_matrix_B_pressure1, eigen_values_pressure1, ...
        error_estimate_pressure1] = ...
        pod_extension_velocity( snapshot_matrix_pressure, paramsP, min_eigen_value, ...
        max_reduced_basis, inner_product_matrix_pressure);
    
    [ reduced_basis_matrix_B_pressure2, eigen_values_pressure2, ...
        error_estimate_pressure2] = ...
        pod_extension( snapshot_matrix_pressure, paramsP, min_eigen_value(1), ...
        max_reduced_basis(1), inner_product_matrix_pressure);