function [ params_reduced, paramsP_reduced, rhs_reduced, ...
    stiffness_matrix_reduced] = galerkin_extension( params, paramsP, ...
    transformed_grid, rhs, stiffness_matrix, B_pressure, B_velocity)
%GALERKIN_EXTENSION Summary of this function goes here
%   Detailed explanation goes here

red_dim_velocity = size(B_velocity,2);
red_dim_pressure = size(B_pressure,2);

rhs_reduced = zeros(red_dim_velocity + red_dim_pressure,1);
rhs_reduced(1:red_dim_velocity) = B_velocity' * rhs(1:params.ndofs);
rhs_reduced(red_dim_velocity + 1:red_dim_velocity + red_dim_pressure) = ...
    B_pressure' * rhs(params.ndofs + 1:params.ndofs + paramsP.ndofs);
stiffness_matrix_reduced = zeros(red_dim_velocity+red_dim_pressure);
stiffness_matrix_reduced(1:red_dim_velocity,1:red_dim_velocity) = ...
    B_velocity' * stiffness_matrix(1:params.ndofs,1:params.ndofs) * ...
    B_velocity;
stiffness_matrix_reduced(1:red_dim_velocity,red_dim_velocity+1:...
    red_dim_velocity + red_dim_pressure) = B_velocity' * ...
    stiffness_matrix(1:params.ndofs,params.ndofs + 1 : ...
    params.ndofs + paramsP.ndofs) * B_pressure;
stiffness_matrix_reduced(red_dim_velocity + 1:red_dim_velocity + ...
    red_dim_pressure, 1:red_dim_velocity) = B_pressure' * ...
    stiffness_matrix(params.ndofs + 1 : params.ndofs + paramsP.ndofs, ...
    1:params.ndofs) * B_velocity;
stiffness_matrix_reduced = sparse(stiffness_matrix_reduced);

params_reduced.ndofs = red_dim_velocity;
paramsP_reduced.ndofs = red_dim_pressure;
params_reduced.dofs = zeros(red_dim_velocity,1);
paramsP_reduced.dofs = zeros(red_dim_pressure,1);
params_reduced.bilinear_side = ...
    stiffness_matrix_reduced(1:red_dim_velocity,1:red_dim_velocity);
params_reduced.bilinear_side_pressure_terms = stiffness_matrix_reduced...
    (1:red_dim_velocity, red_dim_velocity + 1:red_dim_velocity + ...
    red_dim_pressure);
params_reduced.linear_side = rhs_reduced(1:red_dim_velocity);
params_reduced.rhs_continuity = rhs_reduced(red_dim_velocity + 1:...
    red_dim_velocity + red_dim_pressure);
params_reduced.dimrange = params.dimrange;
paramsP_reduced.dimrange = paramsP.dimrange;

[ params_reduced, paramsP_reduced] = solve_plot_solution_schur...
    ( params_reduced, paramsP_reduced, transformed_grid, rhs_reduced, ...
    stiffness_matrix_reduced, 0);

end