function [ transformation_matrix, translation_vector ] = ...
    compute_2d_affine_transformation_matrix( reference_coordinate, ...
    transformed_coordinate)
% Give reference coordinate and tranformed coordinate as 6 \times 1 vector 
% in the form [x_1 y_1 x_2 y_2 x_3 y_3]'.
% It solves an equation of form Ax = b using linsolve.

b = transformed_coordinate;
A = [reference_coordinate(1) reference_coordinate(2) 0 0 1 0;...
    0 0 reference_coordinate(1) reference_coordinate(2) 0 1;...
    reference_coordinate(3) reference_coordinate(4) 0 0 1 0;...
    0 0 reference_coordinate(3) reference_coordinate(4) 0 1;...
    reference_coordinate(5) reference_coordinate(6) 0 0 1 0;...
    0 0 reference_coordinate(5) reference_coordinate(6) 0 1];

x = linsolve(A,b);   

transformation_matrix = [x(1) x(2);x(3) x(4)];

translation_vector = [x(5);x(6)];

end