[ transformed_grid, F_transformation_matrix, ...
    C_translation_vector] = transform_grid( params, grid, mu_x, mu_y);

for i = 1:1:length(F_transformation_matrix)
    para_mapping{i} = inv(F_transformation_matrix{i});
end

plus_plus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_plus_assembly...
    (grid,params);
tic();
plus_plus_assembly_online = ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_plus_assembly_online...
    ( plus_plus_assembly_offline, para_mapping, params, grid, el_subd);
t_end = toc();
disp(['Time for ' ...
    'n_u_tensor_jump_n_phi_tensor_jump_plus_plus_assembly_online : ' ...
    num2str(t_end)]);
plus_plus_assembly_real = n_u_tensor_jump_n_phi_tensor_jump_assembly...
    (transformed_grid,params);
error_affine_plus_plus = max(max(abs(plus_plus_assembly_online - ...
    plus_plus_assembly_real.plus_plus)));

plus_plus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_plus_assembly...
    (transformed_grid,params);
plus_plus_assembly_offline = ...
    plus_plus_assembly_offline.plus_plus_11...
    + plus_plus_assembly_offline.plus_plus_22;
tic();
plus_plus_assembly_real = ...
    n_u_tensor_jump_n_phi_tensor_jump_assembly(transformed_grid,params);
t_end = toc();
disp(['Time for ' ...
    'n_u_tensor_jump_n_phi_tensor_jump_assembly : ', num2str(t_end)]);
close all
error_assembly_plus_plus = ...
    max(max(abs(...
    plus_plus_assembly_offline - plus_plus_assembly_real.plus_plus)));

minus_minus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly...
    (grid,params);
tic();
minus_minus_assembly_online = ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly_online...
    ( minus_minus_assembly_offline, para_mapping, params, grid, el_subd);
t_end = toc();
disp(['Time for ' ...
    'n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly_online : ' ...
    num2str(t_end)]);
minus_minus_assembly_real = n_u_tensor_jump_n_phi_tensor_jump_assembly...
    (transformed_grid,params);
error_affine_minus_minus = max(max(abs(minus_minus_assembly_online - ...
    minus_minus_assembly_real.minus_minus)));

minus_minus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly...
    (transformed_grid,params);
minus_minus_assembly_offline = ...
    minus_minus_assembly_offline.minus_minus_11...
    + minus_minus_assembly_offline.minus_minus_22;
tic();
minus_minus_assembly_real = ...
    n_u_tensor_jump_n_phi_tensor_jump_assembly(transformed_grid,params);
t_end = toc();
disp(['Time for ' ...
    'n_u_tensor_jump_n_phi_tensor_jump_assembly : ', num2str(t_end)]);
close all
error_assembly_minus_minus = ...
    max(max(abs(...
    minus_minus_assembly_offline - minus_minus_assembly_real.minus_minus)));

minus_plus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_plus_assembly...
    (grid,params);
tic();
minus_plus_assembly_online = ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_plus_assembly_online...
    ( minus_plus_assembly_offline, para_mapping, params, grid, el_subd);
t_end = toc();
disp(['Time for ' ...
    'n_u_tensor_jump_n_phi_tensor_jump_minus_plus_assembly_online : ' ...
    num2str(t_end)]);
minus_plus_assembly_real = n_u_tensor_jump_n_phi_tensor_jump_assembly...
    (transformed_grid,params);
error_affine_minus_plus = max(max(abs(minus_plus_assembly_online - ...
    minus_plus_assembly_real.minus_plus)));

minus_plus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_plus_assembly...
    (transformed_grid,params);
minus_plus_assembly_offline = ...
    minus_plus_assembly_offline.minus_plus_11...
    + minus_plus_assembly_offline.minus_plus_22;
tic();
minus_plus_assembly_real = ...
    n_u_tensor_jump_n_phi_tensor_jump_assembly(transformed_grid,params);
t_end = toc();
disp(['Time for ' ...
    'n_u_tensor_jump_n_phi_tensor_jump_assembly : ', num2str(t_end)]);
close all
error_assembly_minus_plus = ...
    max(max(abs(...
    minus_plus_assembly_offline - minus_plus_assembly_real.minus_plus)));

plus_minus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly...
    (grid,params);
tic();
plus_minus_assembly_online = ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly_online...
    ( plus_minus_assembly_offline, para_mapping, params, grid, el_subd);
t_end = toc();
disp(['Time for ' ...
    'n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly_online : ' ...
    num2str(t_end)]);
plus_minus_assembly_real = n_u_tensor_jump_n_phi_tensor_jump_assembly...
    (transformed_grid,params);
error_affine_plus_minus = max(max(abs(plus_minus_assembly_online - ...
    plus_minus_assembly_real.plus_minus)));

plus_minus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly...
    (transformed_grid,params);
plus_minus_assembly_offline = ...
    plus_minus_assembly_offline.plus_minus_11...
    + plus_minus_assembly_offline.plus_minus_22;
tic();
plus_minus_assembly_real = ...
    n_u_tensor_jump_n_phi_tensor_jump_assembly(transformed_grid,params);
t_end = toc();
disp(['Time for ' ...
    'n_u_tensor_jump_n_phi_tensor_jump_assembly : ', num2str(t_end)]);
close all
error_assembly_plus_minus = ...
    max(max(abs(...
    plus_minus_assembly_offline - plus_minus_assembly_real.plus_minus)));

real = n_u_tensor_jump_n_phi_tensor_jump_assembly(transformed_grid,params);
error_total = max(max(abs(plus_plus_assembly_online + minus_minus_assembly_online + ...
    plus_minus_assembly_online + minus_plus_assembly_online - real.res)));