function [ res ] = n_u_tensor_jump_n_phi_tensor_jump_assembly_offline...
    ( params, grid)
%N_U_TENSOR_JUMP_N_PHI_TENSOR_JUMP_ASSEMBLY_OFFLINE Summary of this function goes here
%   Detailed explanation goes here

n_u_tensor_jump_n_phi_tensor_jump_plus_plus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_plus_assembly(grid,params);
n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly(grid,params);
n_u_tensor_jump_n_phi_tensor_jump_minus_plus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_plus_assembly(grid,params);
n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly(grid,params);

n_u_tensor_jump_n_phi_tensor_jump_assembly_offline = ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_plus_assembly_offline.plus_plus_11 + ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_plus_assembly_offline.plus_plus_22 + ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly_offline.plus_minus_11 + ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly_offline.plus_minus_22 + ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_plus_assembly_offline.minus_plus_11 + ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_plus_assembly_offline.minus_plus_22 + ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly_offline.minus_minus_11 + ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly_offline.minus_minus_22;

res.res = n_u_tensor_jump_n_phi_tensor_jump_assembly_offline;
res.plus_plus = n_u_tensor_jump_n_phi_tensor_jump_plus_plus_assembly_offline;
res.plus_minus = n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly_offline;
res.minus_plus = n_u_tensor_jump_n_phi_tensor_jump_minus_plus_assembly_offline;
res.minus_minus = n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly_offline;

close all

end