function [ res ] = n_u_tensor_jump_n_phi_tensor_jump_assembly_online...
    ( offline_assembly_plus_plus, offline_assembly_plus_minus,...
    offline_assembly_minus_plus, offline_assembly_minus_minus, ...
    para_mapping, params, grid, el_subd)
%N_U_TENSOR_JUMP_N_PHI_TENSOR_JUMP_ASSEMBLY_ONLINE Summary of this function goes here
%   Detailed explanation goes here

res = n_u_tensor_jump_n_phi_tensor_jump_plus_plus_assembly_online...
    ( offline_assembly_plus_plus, para_mapping, params, grid, el_subd) + ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly_online...
    ( offline_assembly_plus_minus, para_mapping, params, grid, el_subd) + ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_plus_assembly_online...
    ( offline_assembly_minus_plus, para_mapping, params, grid, el_subd) + ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly_online...
    ( offline_assembly_minus_minus, para_mapping, params, grid, el_subd);

end