function [ res ] = ...
    n_u_tensor_jump_n_phi_tensor_jump_minus_minus_assembly_online...
    ( offline_assembly_minus_minus, para_mapping, params, grid, el_subd)

gids = ldg_global_dof_index(params, grid);

minus_minus_11_assembly = offline_assembly_minus_minus.minus_minus_11;
minus_minus_12_assembly = offline_assembly_minus_minus.minus_minus_12;
minus_minus_21_assembly = offline_assembly_minus_minus.minus_minus_21;
minus_minus_22_assembly = offline_assembly_minus_minus.minus_minus_22;

for i = 1:1:length(el_subd)
    para_mapping{i} = inv(poldecomp(inv(para_mapping{i})));    
end

for i = 1:1:length(el_subd)
    minus_minus_11_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) = ...
        (para_mapping{i}(1,:) * (para_mapping{i}(1,:))') * ...
        minus_minus_11_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) / ...
        det(para_mapping{i})^2;
    minus_minus_12_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) = ...
        (para_mapping{i}(1,:) * (para_mapping{i}(2,:))') * ...
        minus_minus_12_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) / ...
        det(para_mapping{i})^2;
    minus_minus_21_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) = ...
        (para_mapping{i}(2,:) * (para_mapping{i}(1,:))') * ...
        minus_minus_21_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) / ...
        det(para_mapping{i})^2;
    minus_minus_22_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) = ...
        (para_mapping{i}(2,:) * (para_mapping{i}(2,:))') * ...
        minus_minus_22_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) / ...
        det(para_mapping{i})^2;
end

res = minus_minus_11_assembly + minus_minus_12_assembly + ...
    minus_minus_21_assembly + minus_minus_22_assembly;

end