function [ res ] = ...
    n_u_tensor_jump_n_phi_tensor_jump_plus_minus_assembly_online...
    ( offline_assembly_plus_minus, para_mapping, params, grid, el_subd)

gids = ldg_global_dof_index(params, grid);

plus_minus_11_assembly = offline_assembly_plus_minus.plus_minus_11;
plus_minus_12_assembly = offline_assembly_plus_minus.plus_minus_12;
plus_minus_21_assembly = offline_assembly_plus_minus.plus_minus_21;
plus_minus_22_assembly = offline_assembly_plus_minus.plus_minus_22;

for i = 1:1:length(el_subd)
    para_mapping{i} = inv(poldecomp(inv(para_mapping{i})));    
end

for i = 1:1:length(el_subd)
    for j = 1:1:length(el_subd)
        plus_minus_11_assembly(gids(el_subd{j},:),gids(el_subd{i},:)) = ...
            (para_mapping{j}(1,:) * (para_mapping{i}(1,:))') * ...
            plus_minus_11_assembly(gids(el_subd{j},:),gids(el_subd{i},:)) / ...
            (det(para_mapping{i}) * det(para_mapping{j}));
        plus_minus_12_assembly(gids(el_subd{j},:),gids(el_subd{i},:)) = ...
            (para_mapping{j}(2,:) * (para_mapping{i}(1,:))') * ...
            plus_minus_12_assembly(gids(el_subd{j},:),gids(el_subd{i},:)) / ...
            (det(para_mapping{i}) * det(para_mapping{j}));
        plus_minus_21_assembly(gids(el_subd{j},:),gids(el_subd{i},:)) = ...
            (para_mapping{j}(1,:) * (para_mapping{i}(2,:))') * ...
            plus_minus_21_assembly(gids(el_subd{j},:),gids(el_subd{i},:)) / ...
            (det(para_mapping{i}) * det(para_mapping{j}));
        plus_minus_22_assembly(gids(el_subd{j},:),gids(el_subd{i},:)) = ...
            (para_mapping{j}(2,:) * (para_mapping{i}(2,:))') * ...
            plus_minus_22_assembly(gids(el_subd{j},:),gids(el_subd{i},:)) / ...
            (det(para_mapping{i}) * det(para_mapping{j}));
    end
end

res = plus_minus_11_assembly + plus_minus_12_assembly + ...
    plus_minus_21_assembly + plus_minus_22_assembly;

end