psi_del_cdot_phi_offline = ...
    pressure_velocity_continuity_assembly_extension...
    ( params, paramsP, transformed_grid);
psi_del_cdot_phi_offline = psi_del_cdot_phi_offline{1} + ...
    psi_del_cdot_phi_offline{4};
psi_del_cdot_phi_real = pressure_velocity_continuity_assembly...
    (params, paramsP, transformed_grid);
error_assembly_psi_del_cdot_phi_real = ...
    max(max(abs(psi_del_cdot_phi_offline - psi_del_cdot_phi_real)));

tic();
psi_del_cdot_phi_offline = ...
    pressure_velocity_continuity_assembly_extension...
    ( params, paramsP, grid);
t_end = toc();
disp(['Time for pressure_velocity_continuity_assembly_extension : ' ...
    num2str(t_end)]);
tic();
psi_del_cdot_phi_online = ...
    pressure_velocity_continuity_assembly_extension_online...
    ( psi_del_cdot_phi_offline, para_mapping, params, paramsP, ...
    grid, el_subd);
t_end = toc();
disp(['Time for'...
    ' pressure_velocity_continuity_assembly_extension_online : ' ...
    num2str(t_end)]);
psi_del_cdot_phi_real = pressure_velocity_continuity_assembly_extension...
    ( params, paramsP, transformed_grid);
psi_del_cdot_phi_real = psi_del_cdot_phi_real{1} + ...
    psi_del_cdot_phi_real{4};
error_affine_psi_del_cdot_phi_real = ...
    max(max(abs(psi_del_cdot_phi_online - psi_del_cdot_phi_real)));