function save_detailed_simulation_finals(savepath)
% function save_detailed_simulation_final(savepath)
%
% read in the detailed simulations and store final solutions in single
% file. By this faster L2-error determinatio is possible
% test_data is assumed to be generated by save_detailed_simulations before!
%
% files to be generated in the target path:  
%     detail_final.mat  : for all mu, this file contains the final
%                         solution as one column

% This program is open source.  For license terms, see the COPYING file.
%
% --------------------------------------------------------------------
% ATTRIBUTION NOTICE:
% This product includes software developed for the RBmatlab project at
% (C) Universities of Stuttgart and Münster, Germany.
%
% RBmatlab is a MATLAB software package for model reduction with an
% emphasis on Reduced Basis Methods. The project is maintained by
% M. Dihlmann, M. Drohmann, B. Haasdonk, M. Ohlberger and M. Schaefer.
% For Online Documentation and Download we refer to www.morepas.org.
% --------------------------------------------------------------------

  
% Bernard Haasdonk 29.3.2007

if ~exist(savepath,'dir')
  error('data directory does not exist. Please run save_detailed_simulations!')
end;

save(fullfile(savepath,'UNFINISHED.lock'),'savepath');

load(fullfile(savepath,'settings.mat'));

% appropriately size U:
tmp = load(fullfile(savepath,'detail1.mat'));
U = tmp.U(:,end);

% load simulation_data
for mu = 2:size(M,2)
  tmp = load(fullfile(savepath,['detail',num2str(mu),'.mat']));
  U = [U,tmp.U(:,end)];
end;
save(fullfile(savepath,'detail_finals'),'U');

delete(fullfile(savepath,'UNFINISHED.lock'));






% TO BE ADJUSTED TO NEW SYNTAX
%| \docupdate 
