[psi_avg_phi_jump_plus_plus_assembly_offline] = ...
    pressure_average_velocity_basis_jump_assembly_plus_plus...
    (transformed_grid,params,paramsP);
psi_avg_phi_jump_plus_plus_assembly_offline = ...
    psi_avg_phi_jump_plus_plus_assembly_offline.plus_plus_11 + ...
    psi_avg_phi_jump_plus_plus_assembly_offline.plus_plus_22;
[psi_avg_phi_jump_plus_plus_assembly_real] = ...
    pressure_average_velocity_basis_jump_assembly...
    (transformed_grid,params,paramsP);
error_assembly_psi_avg_phi_jump_plus_plus = ...
    max(max(abs( psi_avg_phi_jump_plus_plus_assembly_offline' - ...
    (psi_avg_phi_jump_plus_plus_assembly_real.plus_plus)')));

tic()
[psi_avg_phi_jump_plus_plus_assembly_offline] = ...
    pressure_average_velocity_basis_jump_assembly_plus_plus...
    (grid,params,paramsP);
t_end = toc();
disp(['Time for pressure_average_velocity_basis_jump_assembly'...
    '_plus_plus : ', num2str(t_end)]);
tic()
[psi_avg_phi_jump_plus_plus_assembly_online] = ...
    pressure_average_velocity_basis_jump_assembly_plus_plus_online...
    ( psi_avg_phi_jump_plus_plus_assembly_offline, para_mapping, ...
    params, grid, el_subd );
t_end = toc();
disp(['Time for pressure_average_velocity_basis_jump_assembly'...
    '_plus_plus_online : ',num2str(t_end)]);
[psi_avg_phi_jump_plus_plus_assembly_real] = ...
    pressure_average_velocity_basis_jump_assembly_plus_plus...
    (transformed_grid,params,paramsP);
psi_avg_phi_jump_plus_plus_assembly_real = ...
    psi_avg_phi_jump_plus_plus_assembly_real.plus_plus_11 + ...
    psi_avg_phi_jump_plus_plus_assembly_real.plus_plus_22;
error_affine_psi_avg_phi_jump_plus_plus = ...
    max(max(abs( psi_avg_phi_jump_plus_plus_assembly_online - ...
    (psi_avg_phi_jump_plus_plus_assembly_real)')));

[psi_avg_phi_jump_plus_minus_assembly_offline] = ...
    pressure_average_velocity_basis_jump_assembly_plus_minus...
    (transformed_grid,params,paramsP);
psi_avg_phi_jump_plus_minus_assembly_offline = ...
    psi_avg_phi_jump_plus_minus_assembly_offline.plus_minus_11 + ...
    psi_avg_phi_jump_plus_minus_assembly_offline.plus_minus_22;
[psi_avg_phi_jump_plus_minus_assembly_real] = ...
    pressure_average_velocity_basis_jump_assembly...
    (transformed_grid,params,paramsP);
error_assembly_psi_avg_phi_jump_plus_minus = ...
    max(max(abs( psi_avg_phi_jump_plus_minus_assembly_offline' - ...
    (psi_avg_phi_jump_plus_minus_assembly_real.plus_minus)')));

tic()
[psi_avg_phi_jump_plus_minus_assembly_offline] = ...
    pressure_average_velocity_basis_jump_assembly_plus_minus...
    (grid,params,paramsP);
t_end = toc();
disp(['Time for pressure_average_velocity_basis_jump_assembly'...
    '_plus_minus : ', num2str(t_end)]);
tic()
[psi_avg_phi_jump_plus_minus_assembly_online] = ...
    pressure_average_velocity_basis_jump_assembly_plus_minus_online...
    ( psi_avg_phi_jump_plus_minus_assembly_offline, para_mapping, ...
    params, grid, el_subd );
t_end = toc();
disp(['Time for pressure_average_velocity_basis_jump_assembly'...
    '_plus_minus_online : ',num2str(t_end)]);
[psi_avg_phi_jump_plus_minus_assembly_real] = ...
    pressure_average_velocity_basis_jump_assembly_plus_minus...
    (transformed_grid,params,paramsP);
psi_avg_phi_jump_plus_minus_assembly_real = ...
    psi_avg_phi_jump_plus_minus_assembly_real.plus_minus_11 + ...
    psi_avg_phi_jump_plus_minus_assembly_real.plus_minus_22;
error_affine_psi_avg_phi_jump_plus_minus = ...
    max(max(abs( psi_avg_phi_jump_plus_minus_assembly_online - ...
    (psi_avg_phi_jump_plus_minus_assembly_real)')));

[psi_avg_phi_jump_minus_plus_assembly_offline] = ...
    pressure_average_velocity_basis_jump_assembly_minus_plus...
    (transformed_grid,params,paramsP);
psi_avg_phi_jump_minus_plus_assembly_offline = ...
    psi_avg_phi_jump_minus_plus_assembly_offline.minus_plus_11 + ...
    psi_avg_phi_jump_minus_plus_assembly_offline.minus_plus_22;
[psi_avg_phi_jump_minus_plus_assembly_real] = ...
    pressure_average_velocity_basis_jump_assembly...
    (transformed_grid,params,paramsP);
error_assembly_psi_avg_phi_jump_minus_plus = ...
    max(max(abs( psi_avg_phi_jump_minus_plus_assembly_offline' - ...
    (psi_avg_phi_jump_minus_plus_assembly_real.minus_plus)')));

tic()
[psi_avg_phi_jump_minus_plus_assembly_offline] = ...
    pressure_average_velocity_basis_jump_assembly_minus_plus...
    (grid,params,paramsP);
t_end = toc();
disp(['Time for pressure_average_velocity_basis_jump_assembly'...
    '_minus_plus : ', num2str(t_end)]);
tic()
[psi_avg_phi_jump_minus_plus_assembly_online] = ...
    pressure_average_velocity_basis_jump_assembly_minus_plus_online...
    ( psi_avg_phi_jump_minus_plus_assembly_offline, para_mapping, ...
    params, grid, el_subd );
t_end = toc();
disp(['Time for pressure_average_velocity_basis_jump_assembly'...
    '_minus_plus_online : ',num2str(t_end)]);
[psi_avg_phi_jump_minus_plus_assembly_real] = ...
    pressure_average_velocity_basis_jump_assembly_minus_plus...
    (transformed_grid,params,paramsP);
psi_avg_phi_jump_minus_plus_assembly_real = ...
    psi_avg_phi_jump_minus_plus_assembly_real.minus_plus_11 + ...
    psi_avg_phi_jump_minus_plus_assembly_real.minus_plus_22;
error_affine_psi_avg_phi_jump_minus_plus = ...
    max(max(abs( psi_avg_phi_jump_minus_plus_assembly_online - ...
    (psi_avg_phi_jump_minus_plus_assembly_real)')));

[psi_avg_phi_jump_minus_minus_assembly_offline] = ...
    pressure_average_velocity_basis_jump_assembly_minus_minus...
    (transformed_grid,params,paramsP);
psi_avg_phi_jump_minus_minus_assembly_offline = ...
    psi_avg_phi_jump_minus_minus_assembly_offline.minus_minus_11 + ...
    psi_avg_phi_jump_minus_minus_assembly_offline.minus_minus_22;
[psi_avg_phi_jump_minus_minus_assembly_real] = ...
    pressure_average_velocity_basis_jump_assembly...
    (transformed_grid,params,paramsP);
error_assembly_psi_avg_phi_jump_minus_minus = ...
    max(max(abs( psi_avg_phi_jump_minus_minus_assembly_offline' - ...
    (psi_avg_phi_jump_minus_minus_assembly_real.minus_minus)')));

tic()
[psi_avg_phi_jump_minus_minus_assembly_offline] = ...
    pressure_average_velocity_basis_jump_assembly_minus_minus...
    (grid,params,paramsP);
t_end = toc();
disp(['Time for pressure_average_velocity_basis_jump_assembly'...
    '_minus_minus : ', num2str(t_end)]);
tic()
[psi_avg_phi_jump_minus_minus_assembly_online] = ...
    pressure_average_velocity_basis_jump_assembly_minus_minus_onlin...
    ( psi_avg_phi_jump_minus_minus_assembly_offline, para_mapping, ...
    params, grid, el_subd );
t_end = toc();
disp(['Time for pressure_average_velocity_basis_jump_assembly'...
    '_minus_minus_online : ',num2str(t_end)]);
[psi_avg_phi_jump_minus_minus_assembly_real] = ...
    pressure_average_velocity_basis_jump_assembly_minus_minus...
    (transformed_grid,params,paramsP);
psi_avg_phi_jump_minus_minus_assembly_real = ...
    psi_avg_phi_jump_minus_minus_assembly_real.minus_minus_11 + ...
    psi_avg_phi_jump_minus_minus_assembly_real.minus_minus_22;
error_affine_psi_avg_phi_jump_minus_minus = ...
    max(max(abs( psi_avg_phi_jump_minus_minus_assembly_online - ...
    (psi_avg_phi_jump_minus_minus_assembly_real)')));