function [ res ] = ...
    pressure_average_velocity_basis_jump_assembly_extension_online...
    ( offline_assembly_plus_plus, offline_assembly_plus_minus, ...
    offline_assembly_minus_plus, offline_assembly_minus_minus, ...
    para_mapping, params, grid, el_subd )
%PRESSURE_AVERAGE_VELOCITY_BASIS_JUMP_ASSEMBLY_EXTENSION Summary of this function goes here
%   Detailed explanation goes here

res = ...
    pressure_average_velocity_basis_jump_assembly_plus_plus_online...
    ( offline_assembly_plus_plus, para_mapping, params, grid, el_subd ) + ...
    pressure_average_velocity_basis_jump_assembly_plus_minus_online...
    ( offline_assembly_plus_minus, para_mapping, params, grid, el_subd) + ...
    pressure_average_velocity_basis_jump_assembly_minus_plus_online...
    ( offline_assembly_minus_plus, para_mapping, params, grid, el_subd ) + ...
    pressure_average_velocity_basis_jump_assembly_minus_minus_onlin...
    ( offline_assembly_minus_minus, para_mapping, params, grid, el_subd );

end