function [ res ] = ...
    pressure_average_velocity_basis_jump_assembly_minus_minus_onlin...
    ( offline_assembly_minus_minus, para_mapping, params, grid, el_subd )
%PRESSURE_AVERAGE_VELOCITY_BASIS_JUMP_ASSEMBLY_PLUS_PLUS_ONLINE Summary of this function goes here
%   Detailed explanation goes here

gids_velocity = ldg_global_dof_index(params, grid);
res_minus_minus_11 = (offline_assembly_minus_minus.minus_minus_11)';
res_minus_minus_12 = (offline_assembly_minus_minus.minus_minus_12)';
res_minus_minus_21 = (offline_assembly_minus_minus.minus_minus_21)';
res_minus_minus_22 = (offline_assembly_minus_minus.minus_minus_22)';

for i = 1:1:length(el_subd)
    res_minus_minus_11(gids_velocity(el_subd{i},:),:) = ...
        para_mapping{i}(1,1)...
        * res_minus_minus_11(gids_velocity(el_subd{i},:),:) / ...
        det(para_mapping{i});
    res_minus_minus_12(gids_velocity(el_subd{i},:),:) = ...
        para_mapping{i}(2,1)...
        * res_minus_minus_12(gids_velocity(el_subd{i},:),:) / ...
        det(para_mapping{i});
    res_minus_minus_21(gids_velocity(el_subd{i},:),:) = ...
        para_mapping{i}(1,2)...
        * res_minus_minus_21(gids_velocity(el_subd{i},:),:) / ...
        det(para_mapping{i});
    res_minus_minus_22(gids_velocity(el_subd{i},:),:) = ...
        para_mapping{i}(2,2)...
        * res_minus_minus_22(gids_velocity(el_subd{i},:),:) / ...
        det(para_mapping{i});
end

res = res_minus_minus_11 + res_minus_minus_12 + ...
    res_minus_minus_21 + res_minus_minus_22;

end