function [ stiffness_matrix, params, bilinear_side, diffusive_term, ...
    coercivity_term, flux_approximation, bilinear_side_pressure_terms, ...
    incompressibility_term, pressure_flux_term] = ...
    assemble_stiffness_matrix_extension...
    ( params, paramsP, grid, mu, c11, qdeg)
%ASSEMBLE_STIFFNESS_MATRIX_EXTEN Summary of this function goes here
%   Detailed explanation goes here

if nargin == 5
    qdeg = params.qdeg;
end

[ bilinear_side, diffusive_term, coercivity_term, flux_approximation] = ...
    assemble_bilinear_side_extension( params, paramsP, grid, mu, c11 );
[ bilinear_side_pressure_terms, incompressibility_term, pressure_flux_term ] = ...
    assemble_bilinear_side_pressure_terms_extension...
    ( params, paramsP, grid);
stiffness_matrix = sparse(zeros(params.ndofs+paramsP.ndofs));
stiffness_matrix(1:params.ndofs,1:params.ndofs) = bilinear_side;
stiffness_matrix(1:params.ndofs, ...
    params.ndofs+1:params.ndofs+paramsP.ndofs) = ...
    bilinear_side_pressure_terms';
stiffness_matrix(params.ndofs+1:params.ndofs+paramsP.ndofs,...
    1:params.ndofs) = bilinear_side_pressure_terms;
params.bilinear_side = bilinear_side;
params.bilinear_side_pressure_terms = bilinear_side_pressure_terms';

end