function [ res ] = assemble_bilinear_side_extension_online...
    ( params, paramsP, grid, diffusive_term, coercivity_term, ...
    flux_approximation, para_mapping, el_subd, transformed_grid, c11, mu)
%ASSEMBLE_BILINEAR_SIDE_EXTENSION_ONLINE Summary of this function goes here
%   Detailed explanation goes here

diffusive_term_online = ...
    ldg_evaluate_basis_derivative_assembly_extension_online...
    ( diffusive_term, para_mapping, params, grid, el_subd);

% coercivity_term_online = n_u_tensor_jump_n_phi_tensor_jump_assembly...
%     (transformed_grid, params);

coercivity_term_online.res = n_u_tensor_jump_n_phi_tensor_jump_assembly_online...
    ( coercivity_term.plus_plus, coercivity_term.plus_minus,...
    coercivity_term.minus_plus, coercivity_term.minus_minus, ...
    para_mapping, params, grid, el_subd);

flux_approximation_online = ...
    del_phi_average_n_phi_tensor_jump_assembly_online...
    ( flux_approximation.plus_plus, flux_approximation.plus_minus,...
    flux_approximation.minus_plus, flux_approximation.minus_minus, ...
    para_mapping, params, grid, el_subd);

res = mu * diffusive_term_online + c11 * coercivity_term_online.res - ...
    mu * (flux_approximation_online) - mu * (flux_approximation_online)';

close all

end