function [ res ] = ...
    assemble_bilinear_side_pressure_terms_extension_online...
    ( params, paramsP, grid, incompressibility_term, pressure_flux_term,...
    para_mapping, el_subd)
%ASSEMBLE_BILINEAR_SIDE_PRESSURE_TERMS_EXTENSION_ONLINE Summary of this function goes here
%   Detailed explanation goes here

res = (pressure_velocity_continuity_assembly_extension_online...
    ( incompressibility_term, para_mapping, params, paramsP, ...
    grid, el_subd))' + ...
    pressure_average_velocity_basis_jump_assembly_extension_online...
    ( pressure_flux_term.plus_plus, pressure_flux_term.plus_minus, ...
    pressure_flux_term.minus_plus, pressure_flux_term.minus_minus, ...
    para_mapping, params, grid, el_subd );

close all

end