function [ rhs_online, params ] = assemble_rhs_online_extension...
    ( params, paramsP, grid, source_vector_offline, ...
    linear_side_offline, el_subd, para_mapping, linear_side_continuity)
%ASSEMBLE_RHS_ONLINE_EXTENSION Summary of this function goes here
%   Detailed explanation goes here

rhs_online = zeros(params.ndofs + paramsP.ndofs,1);
linear_side_online = assemble_linear_side_extension_online...
    ( params, paramsP, grid, source_vector_offline, ...
    linear_side_offline, el_subd, para_mapping );
rhs_online(1:params.ndofs,1) = linear_side_online;
rhs_online(params.ndofs+1:params.ndofs+paramsP.ndofs,1) = ...
    linear_side_continuity;
params.linear_side = rhs_online(1:params.ndofs);
params.rhs_continuity = rhs_online(params.ndofs+1:...
    params.ndofs + paramsP.ndofs);

end