function [ res, res1, res2 ] = ...
    assemble_bilinear_side_pressure_terms_extension...
    ( params, paramsP, grid)
%ASSEMBLE_BILINEAR_SIDE_PRESSURE_TERMS_EXTENSION Summary of this function goes here
%   Detailed explanation goes here

res1 = pressure_velocity_continuity_assembly_extension...
    ( params, paramsP, grid);

res2.plus_plus = pressure_average_velocity_basis_jump_assembly_plus_plus...
    (grid,params,paramsP);
res2.plus_minus = pressure_average_velocity_basis_jump_assembly_plus_minus...
    (grid,params,paramsP);
res2.minus_plus = pressure_average_velocity_basis_jump_assembly_minus_plus...
    (grid,params,paramsP);
res2.minus_minus = pressure_average_velocity_basis_jump_assembly_minus_minus...
    ( grid, params, paramsP);

res = res2.plus_plus.plus_plus_11 + res2.plus_plus.plus_plus_22 + ...
    res2.plus_minus.plus_minus_11 + res2.plus_minus.plus_minus_22 + ...
    res2.minus_plus.minus_plus_11 + res2.minus_plus.minus_plus_22 + ...
    res2.minus_minus.minus_minus_11 + res2.minus_minus.minus_minus_22;

res = res + res1{1} + res1{4};

close all

end