[ res, res1, res2 ] = ...
    assemble_bilinear_side_pressure_terms_extension...
    ( params, paramsP, grid);
[ res_real ] = assemble_bilinear_side_pressure_terms...
    ( params, paramsP, grid);
error_assembly_bilinear_pressure_terms = max(max(abs(res - res_real')));

[ res ] = ...
    assemble_bilinear_side_pressure_terms_extension_online...
    ( params, paramsP, grid, res1, res2, para_mapping, el_subd);
[ res_real ] = assemble_bilinear_side_pressure_terms...
    ( params, paramsP, transformed_grid);
error_affine_bilinear_pressure_terms = max(max(abs(res - res_real)));