% % %%%%%%%% Stiffness matrix and rhs check
[ params, paramsP, rhs_real, stifness_matrix_real] = ...
    assemble_stifness_matrix...
    ( params, paramsP, grid, params.qdeg, mu, c11 );
error_rhs_assembly = max(abs(rhs - rhs_real));
error_stiffness_matrix_assembly = max(max(abs(stiffness_matrix_offline ...
    - stifness_matrix_real)));

[ params, paramsP, rhs_real, stifness_matrix_real] = ...
    assemble_stifness_matrix...
    ( params, paramsP, transformed_grid, params.qdeg, mu, c11 );
error_rhs_affine = max(abs(rhs_online - rhs_real));
error_stiffness_matrix_affine = max(max(abs(stiffness_matrix_online ...
    - stifness_matrix_real)));

[ params, paramsP, rhs_real, stifness_matrix_real] = ...
    assemble_stifness_matrix...
    ( params, paramsP, grid, params.qdeg, mu, c11 );
error_rhs_assembly = max(abs(rhs - rhs_real));
error_stiffness_matrix_assembly = max(max(abs(stiffness_matrix_offline ...
    - stifness_matrix_real)));

[ params, paramsP, rhs_real, stifness_matrix_real] = ...
    assemble_stifness_matrix...
    ( params, paramsP, transformed_grid, params.qdeg, mu, c11 );
error_rhs_affine = max(abs(rhs_online - rhs_real));
error_stiffness_matrix_affine = max(max(abs(stiffness_matrix_online ...
    - stifness_matrix_real)));

[ params, paramsP] = solve_plot_solution_schur...
    ( params, paramsP, grid, rhs, stiffness_matrix_offline);