[bilinear_side_extension, diffusive_term, coercivity_term, ...
    flux_approximation] = assemble_bilinear_side_extension...
    ( params, paramsP, grid, mu, c11 );
bilinear_side = assemble_bilinear_side...
    ( grid, params, paramsP, params.qdeg, mu, c11);
error_assembly_bilinear_side = max(max(abs(bilinear_side_extension - ...
    bilinear_side)));

bilinear_side_online = assemble_bilinear_side_extension_online...
    ( params, paramsP, grid, diffusive_term, ...
    coercivity_term, flux_approximation, para_mapping, el_subd, ...
    transformed_grid, c11, mu);
bilinear_side_extension = assemble_bilinear_side_extension...
    ( params, paramsP, transformed_grid, mu, c11 );
error_affine_bilinear_side = max(max(abs(bilinear_side_online - ...
    bilinear_side_extension)));