[ offline_rhs_vector, source_vector_offline, res2, res3, res4 ] = ...
    assemble_linear_side_extension( params, paramsP, grid, mu, c11 );
[ res, res1, res2, res3, res4 ] = assemble_linear_side...
    ( grid, params, paramsP, params.qdeg, mu, c11);
error_assembly_linear_side = max(abs(offline_rhs_vector - res));

[ linear_side_online ] = assemble_linear_side_extension_online...
    ( params, paramsP, grid, source_vector_offline, ...
    offline_rhs_vector, el_subd, para_mapping );
[ res, res1, res2, res3, res4 ] = assemble_linear_side...
    ( transformed_grid, params, paramsP, params.qdeg, mu, c11);
error_affine_linear_side = max(abs(linear_side_online - res));