[del_phi_avg_n_phi_jump_plus_plus_assembly_offline] = ...
    del_u_average_n_v_tensor_jump_plus_plus_assembly(grid,params);
[del_phi_avg_n_phi_jump_plus_minus_assembly_offline] = ...
    del_u_average_n_v_tensor_jump_plus_minus_assembly(grid,params);
[del_phi_avg_n_phi_jump_minus_plus_assembly_offline] = ...
    del_u_average_n_v_tensor_jump_minus_plus_assembly(grid,params);
[del_phi_avg_n_phi_jump_minus_minus_assembly_offline] = ...
    del_u_average_n_v_tensor_jump_minus_minus_assembly(grid,params);
del_phi_avg_n_phi_jump_offline = ...
    del_phi_avg_n_phi_jump_plus_plus_assembly_offline.plus_plus_11 + ...
    del_phi_avg_n_phi_jump_plus_plus_assembly_offline.plus_plus_22 + ...
    del_phi_avg_n_phi_jump_plus_minus_assembly_offline.plus_minus_11 + ...
    del_phi_avg_n_phi_jump_plus_minus_assembly_offline.plus_minus_22 + ...
    del_phi_avg_n_phi_jump_minus_plus_assembly_offline.minus_plus_11 + ...
    del_phi_avg_n_phi_jump_minus_plus_assembly_offline.minus_plus_22 + ...
    del_phi_avg_n_phi_jump_minus_minus_assembly_offline.minus_minus_11 + ...
    del_phi_avg_n_phi_jump_minus_minus_assembly_offline.minus_minus_22;
del_phi_avg_n_phi_jump_real = ...
    del_u_average_n_v_tensor_jump_assembly(grid,params);
close all
error_assembly_del_phi_avg_n_phi_jump_assembly = max(max(abs(...
    del_phi_avg_n_phi_jump_offline - del_phi_avg_n_phi_jump_real.res)));

tic();
[ del_phi_avg_n_phi_jump_online ] = ...
    del_phi_average_n_phi_tensor_jump_assembly_online...
    ( del_phi_avg_n_phi_jump_plus_plus_assembly_offline, ...
    del_phi_avg_n_phi_jump_plus_minus_assembly_offline,...
    del_phi_avg_n_phi_jump_minus_plus_assembly_offline,...
    del_phi_avg_n_phi_jump_minus_minus_assembly_offline, ...
    para_mapping, params, grid, el_subd);
t_end = toc();
disp(['Time for ' ...
    'del_phi_average_n_phi_tensor_jump_assembly_online : ',num2str(t_end)]);
tic();
[del_phi_avg_n_phi_jump_real] = ...
    del_u_average_n_v_tensor_jump_assembly(transformed_grid,params);
t_end = toc();
disp(['Time for ' ...
    'del_u_average_n_v_tensor_jump_assembly : ' ...
    num2str(t_end)]);
close all
error_affine_del_phi_avg_n_phi_jump_assembly = max(max(abs(...
    del_phi_avg_n_phi_jump_online - del_phi_avg_n_phi_jump_real.res)));