function [ res ] = del_phi_average_n_phi_tensor_jump_assembly_offline...
    ( params, grid )
%DEL_PHI_AVERAGE_N_PHI_TENSOR_JUMP_ASSEMBLY_OFFLINE Summary of this function goes here
%   Detailed explanation goes here
[del_phi_avg_n_phi_jump_plus_plus_assembly_offline] = ...
    del_u_average_n_v_tensor_jump_plus_plus_assembly(grid,params);
[del_phi_avg_n_phi_jump_plus_minus_assembly_offline] = ...
    del_u_average_n_v_tensor_jump_plus_minus_assembly(grid,params);
[del_phi_avg_n_phi_jump_minus_plus_assembly_offline] = ...
    del_u_average_n_v_tensor_jump_minus_plus_assembly(grid,params);
[del_phi_avg_n_phi_jump_minus_minus_assembly_offline] = ...
    del_u_average_n_v_tensor_jump_minus_minus_assembly(grid,params);
del_phi_avg_n_phi_jump_offline = ...
    del_phi_avg_n_phi_jump_plus_plus_assembly_offline.plus_plus_11 + ...
    del_phi_avg_n_phi_jump_plus_plus_assembly_offline.plus_plus_22 + ...
    del_phi_avg_n_phi_jump_plus_minus_assembly_offline.plus_minus_11 + ...
    del_phi_avg_n_phi_jump_plus_minus_assembly_offline.plus_minus_22 + ...
    del_phi_avg_n_phi_jump_minus_plus_assembly_offline.minus_plus_11 + ...
    del_phi_avg_n_phi_jump_minus_plus_assembly_offline.minus_plus_22 + ...
    del_phi_avg_n_phi_jump_minus_minus_assembly_offline.minus_minus_11 + ...
    del_phi_avg_n_phi_jump_minus_minus_assembly_offline.minus_minus_22;

res.res = del_phi_avg_n_phi_jump_offline;
res.plus_plus = del_phi_avg_n_phi_jump_plus_plus_assembly_offline;
res.plus_minus = del_phi_avg_n_phi_jump_plus_minus_assembly_offline;
res.minus_plus = del_phi_avg_n_phi_jump_minus_plus_assembly_offline;
res.minus_minus = del_phi_avg_n_phi_jump_minus_minus_assembly_offline;

close all

end