function [ res ] = del_phi_average_n_phi_tensor_jump_assembly_online...
    ( offline_assembly_plus_plus, offline_assembly_plus_minus,...
    offline_assembly_minus_plus, offline_assembly_minus_minus, ...
    para_mapping, params, grid, el_subd)
%DEL_PHI_AVERAGE_N_PHI_TENSOR_JUMP_ASSEMBLY_ONLINE Summary of this function goes here
%   Detailed explanation goes here

res = del_phi_average_n_phi_tensor_jump_plus_plus_assembly...
    ( offline_assembly_plus_plus, para_mapping, params, grid, el_subd) + ...
    del_phi_average_n_phi_tensor_jump_minus_minus_assembly...
    ( offline_assembly_minus_minus, para_mapping, params, grid, el_subd) + ...
    del_phi_average_n_phi_tensor_jump_plus_minus_assembly...
    ( offline_assembly_plus_minus, para_mapping, params, grid, el_subd) + ...
    del_phi_average_n_phi_tensor_jump_minus_plus_assembly...
    ( offline_assembly_minus_plus, para_mapping, params, grid, el_subd);


end