function [ res ] = ...
    del_phi_average_n_phi_tensor_jump_minus_minus_assembly...
    ( offline_assembly_minus_minus, para_mapping, params, grid, el_subd)
%DEL_PHI_AVERAGE_N_PHI_TENSOR_JUMP_PLUS_PLUS_ASSEMBLY Summary of this function goes here
%   Detailed explanation goes here

gids = ldg_global_dof_index(params, grid);

minus_minus_11_assembly = offline_assembly_minus_minus.minus_minus_11;
minus_minus_12_assembly = offline_assembly_minus_minus.minus_minus_12;
minus_minus_21_assembly = offline_assembly_minus_minus.minus_minus_21;
minus_minus_22_assembly = offline_assembly_minus_minus.minus_minus_22;

for i = 1:1:length(el_subd)
    minus_minus_11_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) = ...
        para_mapping{i}(1,:) * (para_mapping{i}(1,:))' * ...
        minus_minus_11_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) / ...
        det(para_mapping{i});
    minus_minus_12_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) = ...
        para_mapping{i}(1,:) * (para_mapping{i}(2,:))' * ...
        minus_minus_12_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) / ...
        det(para_mapping{i});
    minus_minus_21_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) = ...
        para_mapping{i}(2,:) * (para_mapping{i}(1,:))' * ...
        minus_minus_21_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) / ...
        det(para_mapping{i});
    minus_minus_22_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) = ...
        para_mapping{i}(2,:) * (para_mapping{i}(2,:))' * ...
        minus_minus_22_assembly(gids(el_subd{i},:),gids(el_subd{i},:)) / ...
        det(para_mapping{i});    
end

res = minus_minus_11_assembly + minus_minus_12_assembly + ...
    minus_minus_21_assembly + minus_minus_22_assembly;

end