function [ res ] = ...
    del_phi_average_n_phi_tensor_jump_plus_minus_assembly...
    ( offline_assembly_plus_minus, para_mapping, params, grid, el_subd)
%DEL_PHI_AVERAGE_N_PHI_TENSOR_JUMP_PLUS_PLUS_ASSEMBLY Summary of this function goes here
%   Detailed explanation goes here

gids = ldg_global_dof_index(params, grid);

plus_minus_11_assembly = offline_assembly_plus_minus.plus_minus_11;
plus_minus_12_assembly = offline_assembly_plus_minus.plus_minus_12;
plus_minus_21_assembly = offline_assembly_plus_minus.plus_minus_21;
plus_minus_22_assembly = offline_assembly_plus_minus.plus_minus_22;

for i = 1:1:length(el_subd)
    for j = 1:1:length(el_subd)
        plus_minus_11_assembly(gids(el_subd{i},:),gids(el_subd{j},:)) = ...
            (para_mapping{i}(1,:)) * (para_mapping{j}(1,:))' * ...
            plus_minus_11_assembly(gids(el_subd{i},:),gids(el_subd{j},:)) / ...
            det(para_mapping{i});
        plus_minus_12_assembly(gids(el_subd{i},:),gids(el_subd{j},:)) = ...
            (para_mapping{i}(1,:)) * (para_mapping{j}(2,:))' * ...
            plus_minus_12_assembly(gids(el_subd{i},:),gids(el_subd{j},:)) / ...
            det(para_mapping{i});
        plus_minus_21_assembly(gids(el_subd{i},:),gids(el_subd{j},:)) = ...
            (para_mapping{i}(2,:)) * (para_mapping{j}(1,:))' * ...
            plus_minus_21_assembly(gids(el_subd{i},:),gids(el_subd{j},:)) / ...
            det(para_mapping{i});
        plus_minus_22_assembly(gids(el_subd{i},:),gids(el_subd{j},:)) = ...
            (para_mapping{i}(2,:)) * (para_mapping{j}(2,:))' * ...
            plus_minus_22_assembly(gids(el_subd{i},:),gids(el_subd{j},:)) / ...
            det(para_mapping{i});
    end
end

res = plus_minus_11_assembly + plus_minus_12_assembly + ...
    plus_minus_21_assembly + plus_minus_22_assembly;

end