del_phi_del_u_matrix_offline = ...
    ldg_evaluate_basis_derivative_assembly_extension( params, ...
    transformed_grid);
del_phi_del_u_matrix_offline = del_phi_del_u_matrix_offline{1} + ...
    del_phi_del_u_matrix_offline{4};
del_phi_del_u_matrix_real = ldg_evaluate_basis_derivative_assembly...
    (params, transformed_grid);
error_assembly_del_phi_del_u_matrix = ...
    max(max(abs(del_phi_del_u_matrix_offline - ...
    del_phi_del_u_matrix_real)));

tic();
del_phi_del_u_matrix_offline = ...
    ldg_evaluate_basis_derivative_assembly_extension( params, grid);
t_end = toc();
disp(['Time for ldg_evaluate_basis_derivative_assembly_extension : ' ...
    num2str(t_end)]);
tic();
del_phi_del_u_matrix_online = ...
    ldg_evaluate_basis_derivative_assembly_extension_online...
    ( del_phi_del_u_matrix_offline, para_mapping, params, grid, el_subd);
t_end = toc();
disp(['Time for ldg_evaluate_basis_derivative_assembly_extension_online : ' ...
    num2str(t_end)]);
del_phi_del_u_matrix_real = ...
    ldg_evaluate_basis_derivative_assembly_extension...
    (params, transformed_grid);
del_phi_del_u_matrix_real = ...
    del_phi_del_u_matrix_real{1} + del_phi_del_u_matrix_real{4};
error_affine_del_phi_del_u_matrix = ...
    max(max(abs(del_phi_del_u_matrix_online - ...
    del_phi_del_u_matrix_real)));